# Schema for the configuration files of the File checker module.

file_checker.settings:
  type: config_object
  label: 'File checker settings'
  mapping:
    check_on_change:
      type: string
      label: 'Check files when stored location changes?'