module:
  AppScan_Shield: 0
  XSS_Shield: 0
  admin_toolbar: 0
  automated_cron: 0
  back_to_top: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  color_field: 0
  comment: 0
  conditional_fields: 0
  config: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  current_aq_data_module: 0
  datetime: 0
  dblog: 0
  disable_messages: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  forecast_aq_data_module: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  link: 0
  marquee_data_module: 0
  media: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  partners: 0
  path: 0
  path_alias: 0
  publications_pages: 0
  quickedit: 0
  recent_trends: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  site_map: 0
  state_pages: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_static_cron: 0
  tome_static_super_cache: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  twig_extension_helper: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  url_redirect: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  weight: 0
  which_flag: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  anblue: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
